# Generated by Django 4.0.1 on 2022-02-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='Habiliadad')),
            ],
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ('-first_name', 'last_name'), 'verbose_name': 'Mi Empleado', 'verbose_name_plural': 'Mis empleados'},
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('first_name', 'last_name')},
        ),
    ]
