# Generated by Django 4.0.2 on 2022-02-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'Analista Jr'), ('1', 'Analista'), ('2', 'Consultor'), ('3', 'Consultor Senior'), ('4', 'Coordinador')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
